### PR TITLE
Added Hospital Details Page

### LINKED ISSUE #37: Hospital Details Page
12-Hospital Detail page

### PR DESCRIPTION
**Pull request by Shubham-1105**
closes #37 
Screenshot_2020-11-02-03-00-06-121_com example frontend

### CODE REVIEW

**Comment by Shubham-1105** [comment]
@carrisunrio any changes to be made in the UI?

**Comment by suntwalriya** [comment]
the buttons at the bottom, you have made them under the section of department , they should be concluding the page.

**Comment by Shubham-1105** [comment]
fixes #44 and #74

**Comment by suntwalriya** [comment]
@Shubham-1105 you cannot close any issue. Kindly follow the rules make a PR with a screenshot. Make a new PR with a Screenshot attached!

**Pull request closed without merging**
