### PR TITLE
Manthan109

### PR DESCRIPTION
**Pull request by manthanguptaa**
Project Setup for flutter frontend

### CODE REVIEW

**Comment by manthanguptaa** [comment]
Screenshot_2020-10-26-18-38-37-439_com example frontend
Login Page

**Comment by manthanguptaa** [comment]
Screenshot_2020-10-26-19-19-47-717_com example frontend
Require app logo to complete the dashboard

**Review by suntwalriya — CHANGES_REQUESTED** [review]
in color.dart : line no. 7 blue to aqua(#00ffff)

**Comment by manthanguptaa** [comment]
Screenshot_2020-10-27-20-19-34-494_com example frontend
Requested changes are done

**Comment by manthanguptaa** [comment]
Screenshot_2020-10-27-20-54-54-118_com example frontend

**Pull request merged**
