### PR TITLE
Wireframe 1.0

### LINKED ISSUE #99: Doctor's list
The following should be made w.r.t the UI for a mobile device for the user-side with same colour combination as mentioned in the file structure.
image
image

### PR DESCRIPTION
**Pull request by Albert-Jokelin**

### CODE REVIEW

**Review by suntwalriya — COMMENTED** [review]
Nice Work @Albert-Jokelin 👍 We will discuss more about this with the team at 5 pm today in the meeting. Hope to see you there.

**Comment by suntwalriya** [comment]
@Albert-Jokelin any updates?

**Comment by Albert-Jokelin** [comment]
Hey!
The designing is moving at a slower pace because I have vivas and assignment submission going on. I'll try to finish it within two days.

**Comment by suntwalriya** [comment]
No issues!

**Comment by suntwalriya** [comment]
@Albert-Jokelin You were supposed make PR in contibuation this one. Please refrain making a new one and add it here again. So that i can merge and close this one.

**Comment by Albert-Jokelin** [comment]
I apologize for the mistake. I've updated the files. Please go through them and let me know if any changes are needed.

**Comment by suntwalriya** [comment]
I have checked them. I will merge this as well.

**Pull request merged**
