### PR TITLE
fix: file structure updated

### PR DESCRIPTION
**Pull request by Arnab-31**
image

### CODE REVIEW

**Comment by Arnab-31** [comment]
Should I also update the readme.md about how to run the server locally?

**Comment by BhavyaaArora-08** [comment]
Yes

**Comment by Arnab-31** [comment]
@Codess08 It's done.

**Comment by mbcse** [comment]
@Arnab-31 why you have put the config folder and package.json file outside the server folder,
All server code will be in the server folder and all codebase(including config,lib,server.js, etc) will be in src(src means source code of server), just keep package.json file outside src folder, in the server folder

**Comment by Arnab-31** [comment]
If we keep the package.json file inside the server folder, then to start the server every time we need to be in the server folder and not in the root,  will that be fine?

**Comment by mbcse** [comment]
Yes, actually server folder is just to differentiate backend code from frontend, later it will be deployed Individually

**Comment by Arnab-31** [comment]
image
 Is this alright?

**Comment by mbcse** [comment]
Yes looks fine @Arnab-31, just remove the db folder

**Pull request merged**
