### PR TITLE
Added drawer with code and screenshot

### PR DESCRIPTION
**Pull request by Geeky-star**

### CODE REVIEW

**Comment by manthanguptaa** [comment]
Can you attach the photo of the file architecture you are following

**Comment by Geeky-star** [comment]
> Can you attach the photo of the file architecture you are following

Screenshot (1)

**Comment by manthanguptaa** [comment]
This is not the right way to write a modular code. Check my pull request and the way code is written

**Comment by samflab** [comment]
please do not code directly in the main.dart file, please make file and call it in main.dart

**Pull request closed without merging**
